VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "labvm"
  config.vm.box = "generic/debian12"
  config.vm.hostname = "labvm"
  config.ssh.insert_key = false

  # Virtualbox config
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end

  # Network config
  # config.vm.network :private_network, ip: "xx.xx.xx.xx"

  # Sync Folder config
  config.vm.synced_folder "./../../jenkins-vm/jenkins-config", "/home/vagrant/jenkins-config", owner: "vagrant", group: "vagrant"

  # # Executing a shell script
  config.vm.provision "shell", privileged: true, path: "./../../jenkins-vm/jenkins-config/script.sh"
end
